api_root_path: /
auto_reload: false
cors_allow_credentials: null
cors_allowed_headers: null
cors_allowed_methods: null
cors_allowed_origins: null
crypt4gh_public_key: dWoWghAEVPcpHILEb5drJx59nF+of6YKuAOhKRpmegY=
docs_url: /docs
host: 127.0.0.1
log_level: info
openapi_url: /openapi.json
port: 8080
service_name: wkvs
workers: 1
