info:
  title: FastAPI
  version: 0.1.0
openapi: 3.0.2
paths:
  /:
    get:
      description: Greet the World
      operationId: index__get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Greet the world
