[project]
name = "wkvs"
version = "1.1.1"
description = "Well-Known-Value-Service - Provides access to common values via API"
dependencies = [
    "ghga-service-commons[api]>=3.1",
    "hexkit>=3.3",
    "typer>=0.12",
]

[project.urls]
Repository = "https://github.com/ghga-de/well-known-value-service"

[project.scripts]
wkvs = "wkvs.__main__:cli"
