[project]
name = "wkvs"
version = "1.1.3"
description = "Well-Known-Value-Service - Provides access to common values via API"
dependencies = [
    "ghga-service-commons[api]>=4.0.0",
    "hexkit>=4.3.1",
    "typer>=0.15.2",
]

[project.urls]
Repository = "https://github.com/ghga-de/well-known-value-service"

[project.scripts]
wkvs = "wkvs.__main__:cli"
