[project]
name = "wkvs"
version = "1.2.3"
description = "Well-Known-Value-Service - Provides access to common values via API"
dependencies = [
    "ghga-service-commons[api]>=5.1",
    "hexkit>=7.1",
    "typer>=0.19",
]

[project.urls]
Repository = "https://github.com/ghga-de/well-known-value-service"

[project.scripts]
wkvs = "wkvs.__main__:cli"
